# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: תחבורה ציבורית בשבת - סטטוס קוו 
lang: he_IL
name: תחבורה ציבורית בשבת - סטטוס קוו
email: contact@quo-il.org
description: >- 
  מה ההשלכות שלו לגבי תחבורה ציבורית בשבת?
  מהו סטטוס קוו?
  מה הפולטיקאים עושים לגבי זה?
  מה העמדות שלהם?
baseurl: "" # the subpath of your site, e.g. /blog


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

google_analytics: true
webmaster_verifications:
  google: VBMqxURnNCh_rFOjCqEsTbLXPviVjOnw2yGj58rACZA
  # bing: 1234
  # alexa: 1234
  # yandex: 1234
  # baidu: 1234

collections:
  basics:
    output: false
  parties:
    output: true
    permalink: /מפלגות/:name
  people:
    output: true
    permalink: /פוליטיקאים/:name


exclude:
  - "*.sh"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
